name: Sync FongMi Branch

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  sync-fongmi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        ref: fongmi
        
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/FongMi/Release.git
        git fetch upstream fongmi
        
    - name: Reset to upstream branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git reset --hard upstream/fongmi
        
    - name: Push to target repo
      run: |
        git push origin fongmi --force
