name: 同步FongMi

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  同步fongmi:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出当前仓库
      uses: actions/checkout@v4
      with:
        ref: fongmi
        
    - name: 添加上游远程仓库
      run: |
        git remote add upstream https://github.com/FongMi/Release.git
        git fetch upstream fongmi
        
    - name: 重置到上游分支
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git reset --hard upstream/fongmi
        
    - name: 推送到目标仓库
      run: |
        git push origin fongmi --force
